CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
     ID UUID PRIMARY KEY,
     NAME VARCHAR,
     CREATED_AT BIGINT,
     UPDATED_AT BIGINT,
     CREATED_BY UUID,
     UPDATED_BY UUID
);

CREATE TABLE IF NOT EXISTS ROLES(
    ID UUID PRIMARY KEY,
    NAME VARCHAR UNIQUE,
    CREATED_AT BIGINT,
    UPDATED_AT BIGINT,
    CREATED_BY UUID,
    UPDATED_BY UUID
);

CREATE TABLE IF NOT EXISTS USERS(
    ID UUID PRIMARY KEY,
    NAME VARCHAR,
    EMAIL VARCHAR UNIQUE NOT NULL,
    PASSWORD VARCHAR,
    ORGANIZATION_ID UUID NOT NULL REFERENCES ORGANIZATIONS(ID),
    ROLE_ID UUID NOT NULL REFERENCES ROLES(ID),
    CREATED_AT BIGINT,
    UPDATED_AT BIGINT,
    CREATED_BY UUID,
    UPDATED_BY UUID
);
